/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aptekaprogram;

import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;

/**
 *
 * @author Sebcio
 */
public class AddRecepta extends javax.swing.JFrame {

    /**
     * Creates new form AddRecepta
     */
    public AddRecepta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        AptekaProgramPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("AptekaProgramPU").createEntityManager();
        klientQuery = java.beans.Beans.isDesignTime() ? null : AptekaProgramPUEntityManager.createQuery("SELECT k FROM Klient k");
        klientList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : klientQuery.getResultList();
        receptaQuery = java.beans.Beans.isDesignTime() ? null : AptekaProgramPUEntityManager.createQuery("SELECT r FROM Recepta r");
        receptaList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : receptaQuery.getResultList();
        klientQuery1 = java.beans.Beans.isDesignTime() ? null : AptekaProgramPUEntityManager.createQuery("SELECT k FROM Klient k");
        klientList1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : klientQuery1.getResultList();
        klientQuery2 = java.beans.Beans.isDesignTime() ? null : AptekaProgramPUEntityManager.createQuery("SELECT k FROM Klient k");
        klientList2 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : klientQuery2.getResultList();
        jLabel1 = new javax.swing.JLabel();
        LekiRecepta = new javax.swing.JTextField();
        WprowadzRecepte = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        KlientRecepta = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Leki");

        WprowadzRecepte.setText("Wprowadz");
        WprowadzRecepte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WprowadzRecepteActionPerformed(evt);
            }
        });

        jLabel2.setText("Klient");

        org.jdesktop.swingbinding.JComboBoxBinding jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, klientList2, KlientRecepta);
        bindingGroup.addBinding(jComboBoxBinding);

        KlientRecepta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KlientReceptaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(KlientRecepta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(WprowadzRecepte)
                            .addComponent(LekiRecepta, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {KlientRecepta, LekiRecepta});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(KlientRecepta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(LekiRecepta, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(WprowadzRecepte)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void WprowadzRecepteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WprowadzRecepteActionPerformed
        // TODO add your handling code here:
        Recepta r1 = new Recepta();
        r1.setLeki(LekiRecepta.getText());
        
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("AptekaProgramPU");
        ReceptaJpaController rjc = new ReceptaJpaController(emf);
        rjc.create(r1);

        PokazRecepta pr = new PokazRecepta();
        pr.setVisible(true);
    }//GEN-LAST:event_WprowadzRecepteActionPerformed

    private void KlientReceptaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KlientReceptaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KlientReceptaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddRecepta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddRecepta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddRecepta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddRecepta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddRecepta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager AptekaProgramPUEntityManager;
    private javax.swing.JComboBox<String> KlientRecepta;
    private javax.swing.JTextField LekiRecepta;
    private javax.swing.JButton WprowadzRecepte;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private java.util.List<aptekaprogram.Klient> klientList;
    private java.util.List<aptekaprogram.Klient> klientList1;
    private java.util.List<aptekaprogram.Klient> klientList2;
    private javax.persistence.Query klientQuery;
    private javax.persistence.Query klientQuery1;
    private javax.persistence.Query klientQuery2;
    private java.util.List<aptekaprogram.Recepta> receptaList;
    private javax.persistence.Query receptaQuery;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
